# frozen_string_literal: true

# lib/ruby_pi/context/compaction.rb
#
# RubyPi::Context::Compaction — Token estimation and context window management.
#
# When the conversation history grows too large for the model's context window,
# Compaction summarizes older messages while preserving the most recent ones.
# Token estimation uses a simple heuristic (~4 characters per token) to avoid
# external tokenizer dependencies. When compaction triggers, older messages are
# replaced with a single summary message generated by the LLM, and a :compaction
# event is emitted.

module RubyPi
  module Context
    # Manages context window size by summarizing older messages when the
    # estimated token count exceeds a configurable threshold. The most recent
    # N messages are always preserved to maintain conversational coherence.
    #
    # @example Configuring compaction
    #   compaction = RubyPi::Context::Compaction.new(
    #     max_tokens: 8000,
    #     summary_model: model,
    #     preserve_last_n: 4
    #   )
    #   compacted = compaction.compact(messages, system_prompt)
    class Compaction
      # Average characters per token — a rough heuristic that avoids the need
      # for provider-specific tokenizers. Errs on the conservative side.
      CHARS_PER_TOKEN = 4

      # @return [Integer] the token threshold above which compaction triggers
      attr_reader :max_tokens

      # @return [RubyPi::LLM::BaseProvider] the model used to generate summaries
      attr_reader :summary_model

      # @return [Integer] number of recent messages always preserved
      attr_reader :preserve_last_n

      # @return [#emit, nil] optional event emitter for :compaction events
      attr_accessor :emitter

      # Creates a new Compaction instance.
      #
      # @param max_tokens [Integer] trigger compaction above this token estimate
      #   (default: 8000)
      # @param summary_model [RubyPi::LLM::BaseProvider] model for summarization
      # @param preserve_last_n [Integer] always keep the last N messages
      #   (default: 4)
      def initialize(max_tokens: 8000, summary_model:, preserve_last_n: 4)
        @max_tokens = max_tokens
        @summary_model = summary_model
        @preserve_last_n = preserve_last_n
        @emitter = nil
      end

      # Compacts the message history if the estimated token count exceeds
      # the threshold. Returns the compacted messages array, or nil if no
      # compaction was needed.
      #
      # The compaction process:
      # 1. Estimate total tokens for system_prompt + all messages.
      # 2. If under threshold, return nil (no compaction needed).
      # 3. Split messages into "droppable" (older) and "preserved" (recent).
      # 4. Summarize the droppable messages via the summary model.
      # 5. Return a new array: [summary_message] + preserved_messages.
      #
      # @param messages [Array<Hash>] the current conversation history
      # @param system_prompt [String] the system prompt (included in estimate)
      # @return [Array<Hash>, nil] compacted messages, or nil if not needed
      def compact(messages, system_prompt)
        total_tokens = estimate_tokens(system_prompt, messages)
        return nil if total_tokens <= @max_tokens

        # Split into messages to summarize and messages to keep
        preserved_count = [@preserve_last_n, messages.size].min
        droppable = messages[0...(messages.size - preserved_count)].dup
        preserved = messages[(messages.size - preserved_count)..].dup

        # If there's nothing to drop, we can't compact further
        return nil if droppable.empty?

        # Anthropic and OpenAI both require every tool_result / tool message
        # to reference a tool_use / tool_call from a preceding assistant
        # message. If we summarize the assistant turn that originated a tool
        # call but keep the matching tool_result, the API rejects the
        # request with "tool_result without preceding tool_use".
        #
        # When the boundary between droppable and preserved cuts mid-exchange,
        # preserved can start with one or more orphan :tool messages whose
        # matching assistant turn is in droppable. Strip those off the head of
        # preserved and move them into droppable so they are summarized away
        # rather than sent. Because the originating assistant message is older,
        # it is already in droppable, so the pair stays together there — there
        # is no mirror case to handle (once a tool result is moved across, its
        # assistant is never left stranded on the preserved side).
        while preserved.first && preserved.first[:role] == :tool
          droppable << preserved.shift
        end

        # The orphan-strip only moves messages INTO droppable, so droppable
        # cannot have shrunk; it is still non-empty here. preserved, however,
        # may now be empty (the whole window was tool results) — the summary
        # construction below handles that case.

        # Generate a summary of the dropped messages
        summary = summarize(droppable)

        # Emit compaction event if an emitter is available
        @emitter&.emit(:compaction, dropped_count: droppable.size, summary: summary)

        build_compacted_history(summary, preserved)
      end

      # Builds the compacted history: a summary message followed by the
      # preserved tail.
      #
      # The summary becomes the FIRST message of the compacted history, so it
      # must satisfy the strictest provider constraints (Anthropic):
      #   1. The summary role MUST NOT be :system — that would overwrite the
      #      real system prompt on Anthropic, which promotes the last :system
      #      message to the top-level `system:` parameter.
      #   2. The first message MUST use role :user.
      #   3. Consecutive same-role messages are rejected.
      #
      # A :user summary satisfies (1) and (2). For (3): the orphan-strip above
      # guarantees the first preserved message is :assistant, :user, or absent
      # (never :tool). When it is :assistant or absent, a standalone :user
      # summary alternates correctly. When it is :user, a separate :user
      # summary would create two consecutive user messages, so we instead
      # merge the summary text into that existing user message — keeping the
      # first message a single :user message with no role collision.
      #
      # @param summary [String] the generated summary text
      # @param preserved [Array<Hash>] the preserved tail of messages
      # @return [Array<Hash>] the compacted history
      def build_compacted_history(summary, preserved)
        summary_text = "[Conversation Summary]\n#{summary}"
        first_preserved = preserved.first

        if first_preserved && first_preserved[:role] == :user
          merged = first_preserved.dup
          merged[:content] = "#{summary_text}\n\n#{first_preserved[:content]}"
          [merged] + preserved.drop(1)
        else
          [{ role: :user, content: summary_text }] + preserved
        end
      end

      # Estimates the total token count for a system prompt and message array
      # using the character-based heuristic.
      #
      # @param system_prompt [String] the system prompt text
      # @param messages [Array<Hash>] conversation messages
      # @return [Integer] estimated token count
      def estimate_tokens(system_prompt, messages)
        total_chars = system_prompt.to_s.length

        messages.each do |msg|
          total_chars += msg[:content].to_s.length
          # Account for role and structural overhead (~10 tokens per message)
          total_chars += 40
        end

        (total_chars.to_f / CHARS_PER_TOKEN).ceil
      end

      private

      # Generates a summary of the given messages using the summary model.
      # The summary captures key decisions, facts, and context from the
      # conversation so far.
      #
      # @param messages [Array<Hash>] messages to summarize
      # @return [String] the generated summary text
      def summarize(messages)
        summary_prompt = build_summary_prompt(messages)

        response = @summary_model.complete(
          messages: [
            { role: :system, content: "You are a precise conversation summarizer. " \
              "Produce a concise summary that preserves all important facts, decisions, " \
              "tool results, and context. Do not add any information not present in " \
              "the conversation." },
            { role: :user, content: summary_prompt }
          ],
          tools: [],
          stream: false
        )

        response.content || ""
      end

      # Builds the prompt text for the summarization LLM call by formatting
      # each message into a readable transcript.
      #
      # @param messages [Array<Hash>] messages to include in the transcript
      # @return [String] formatted prompt for summarization
      def build_summary_prompt(messages)
        transcript = messages.map do |msg|
          role = msg[:role].to_s.capitalize
          content = msg[:content].to_s
          "#{role}: #{content}"
        end.join("\n\n")

        "Summarize the following conversation, preserving all key facts, " \
          "decisions, and tool call results:\n\n#{transcript}"
      end
    end
  end
end
